
    flowchart LR
    A[External Tools] --> B[Integration Service]
    B[Integration Service] --> C[Normalization]
    C[Normalization] --> D[Database]
    D[Database] --> E[GraphQL API] --> F[React Frontend]
 
